# Generated by Django 4.1.5 on 2023-05-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='id',
        ),
        migrations.AlterField(
            model_name='login',
            name='Mail',
            field=models.CharField(default=None, max_length=50, primary_key=True, serialize=False),
        ),
    ]
