# Generated by Django 4.1.5 on 2023-05-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0002_remove_login_id_alter_login_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion_Data',
            fields=[
                ('Form_id', models.AutoField(primary_key=True, serialize=False)),
                ('Mail', models.CharField(default=None, max_length=50)),
                ('Title', models.CharField(default=None, max_length=50)),
                ('Description', models.CharField(default=None, max_length=250, null=True)),
                ('Attachment', models.ImageField(blank=True, upload_to='')),
                ('Status_A', models.CharField(default='Pending', max_length=20)),
                ('Manager_mail', models.CharField(default=None, max_length=50, null=True)),
                ('Status_M', models.CharField(default='Pending', max_length=20)),
                ('Answer', models.CharField(default=None, max_length=350, null=True)),
                ('Entry_Time', models.TimeField(default=None)),
            ],
        ),
    ]
