# Generated by Django 4.1.5 on 2023-05-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0003_suggestion_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion_data',
            name='Entry_Time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
