# Generated by Django 4.1.5 on 2023-05-31 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0006_suggestion_data_admin_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestion_data',
            old_name='Answer',
            new_name='Manager_answer',
        ),
    ]
