# Generated by Django 4.1.5 on 2023-06-12 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0008_suggestion_data_anonymous_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion_data',
            name='Anonymous',
        ),
    ]
